export enum MessageCodes {
	RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
	SERVER_ERROR = "SERVER_ERROR",
	MISSING_CONFIGURATION = "MISSING_CONFIGURATION",
	INVALID_AUTH_CODE = "INVALID_AUTH_CODE",
	SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
	PERSON_NOT_FOUND = "PERSON_NOT_FOUND",
	STATE_MISMATCH = "STATE_MISMATCH",
	INVALID_CLAIMED_IDENTITY = "INVALID_CLAIMED_IDENTITY",
	ERROR_SIGNING_VC = "ERROR_SIGNING_VC",
	ERROR_WRITING_TXMA = "ERROR_WRITING_TXMA",
}
