export enum ServicesEnum {
	AUTHORIZATION_SERVICE = "CIC_AUTHORIZATION_SERVICE",
	SESSION_SERVICE = "CIC_SESSION_SERVICE",
	SESSION_CONFIG_SERVICE = "CIC_SESSION_CONFIG_SERVICE",
	ACCESS_TOKEN_SERVICE = "CIC_ACCESS_TOKEN_SERVICE",
	JWKS_SERVICE = "CIC_JWKS_SERVICE",
	USERINFO_SERVICE = "CIC_USER_INFO_SERVICE",
	CLAIMED_IDENTITY_SERVICE = "CIC_CLAIMED_IDENTITY_SERVICE",
	ABORT_SERVICE = "CIC_ABORT_SERVICE",
	NA = "NA",
}
