export enum TxmaEventNames {
	CIC_CRI_START = "CIC_CRI_START",
	CIC_CRI_AUTH_CODE_ISSUED = "CIC_CRI_AUTH_CODE_ISSUED",
	CIC_CRI_VC_ISSUED = "CIC_CRI_VC_ISSUED",
	CIC_CRI_END = "CIC_CRI_END",
	CIC_CRI_SESSION_ABORTED = "CIC_CRI_SESSION_ABORTED",
}
