name: Deploy IPV Stub to Build Env
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
    paths:
      - 'cic-ipv-stub/**'
      - .github/workflows/post-merge-ipv-stub-package-to-build.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env: # Only adding the variables in that are required for
  AWS_REGION: eu-west-2

jobs:
  deploy-to-build:
    name: Validate & Deploy SAM template to Build Environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cic-ipv-stub
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.BUILD_IPV_STUB_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t template.yaml --lint

      - name: Install Nodejs Npm Esbuild Builder
        run: npm -g install esbuild

      - name: Install Dependencies
        run: npm install

      - name: SAM Build
        run: sam build -t template.yaml

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@v3.9.2
        with:
            artifact-bucket-name: ${{ secrets.BUILD_IPV_STUB_ARTIFACT_SOURCE_BUCKET_NAME }}
            signing-profile-name: ${{ secrets.BUILD_CRI_CIC_SIGNING_PROFILE_NAME }}
            working-directory: cic-ipv-stub
            template-file: .aws-sam/build/template.yaml
